Repository lukso-network/lukso-orchestrator, pull requests merged in 2021-11, with the labels that each got.

#79 Added sleep step to GH actions for develop branch
  .github/workflows/deploy.yml
Labels: bug, enhancement

#68 Dehardcode flags
  scripts/lukso
Labels: enhancement

#82 Update v1.7
  scripts/lukso
Labels: enhancement

#97 Update deploy.yml
  .github/workflows/deploy.yml
Labels: bug

#95 Provide vanguard IPC connection flow
  orchestrator/vanguardchain/service.go
Labels: enhancement
